### ISSUE TITLE
ERROR: AT deployment: testDeployTrainedModel.lua

### ISSUE THREAD

**Issue by KanimozhiU** [castorini/MP-CNN-Torch#11]
loading word embeddings	
num test  = 4927
/home/kanimozhiu/torch/install/bin/luajit: /home/kanimozhiu/torch/install/share/lua/5.1/torch/File.lua:259: read error: read 0 blocks instead of 1 at /home/kanimozhiu/torch/pkg/torch/lib/TH/THDiskFile.c:352
stack traceback:
	[C]: in function 'readInt'
	/home/kanimozhiu/torch/install/share/lua/5.1/torch/File.lua:259: in function 'readObject'
	/home/kanimozhiu/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	testDeployTrainedModel.lua:83: in main chunk
	[C]: in function 'dofile'
	...zhiu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d5

I'm a newbie in programming.  Kindly help in resolving this issue?

**Comment by hohoCode** [comment]
Looks to me the trained model is not downloaded as the problem here is "read 0 blocks instead 1".  

It is required to download the trained model first. It is about 500MB. Just put it in the directory and the testDeployTrainedModel.lua file will load it and run everything.

Click the link in README for model download: "The trained model download link is HERE".

**Comment by KanimozhiU** [comment]
Thank you. The code runs now. 
How to use the same code to work on two given sentences irrespective of the domain. No training samples/vocabulary are available. In which the input will a paragraph so that we have to identify the redundant sentences from the input paragraph based on semantic similarity. KIndly help me in modifying your code to solve this task.

**Comment by lintool** [comment]
@KanimozhiU We are happy to help you get our code working and reproduce our results, but it seems like you're asking us to work on your problem, which unfortunately we do not have the resources to do.
