### ISSUE TITLE
Stanford Parser

### ISSUE THREAD

**Issue by nerissad** [castorini/MP-CNN-Torch#8]
The preprocess-sick.py calls a file "DependencyParse.java" . I didn't find two versions of the stanford-parser-full I downloaded from the website. Where can I find this ?

**Comment by hohoCode** [comment]
To use our codes, I do not think you need to run Stanford CoreNLP. We have done the preprocessing on SICK data already. The preprocessed SICK data is in data/ directory. You can simply ignore this DependencyParse file.
